accounts/urls.py
from django.urls import path
from . import views
from .views import TransactionConfirmDeleteView, TransactionListView, InputTransactionView, ConfirmTransactionsView, CustomLoginView, SignUpView, SignUpSuccessView, LogoutView, MyPageView

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signup_success/', SignUpSuccessView.as_view(), name='signup_success'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('my_page/', MyPageView.as_view(), name='my_page'),
    path('home/', views.home, name='home'),
    path('input_transaction/', InputTransactionView.as_view(), name='input_transaction'),
    path('confirm_transactions/', ConfirmTransactionsView.as_view(), name='confirm_transactions'),
    path('transaction_list/', TransactionListView.as_view(), name='transaction_list'),
    path('transaction_confirm_delete/<int:pk>/', TransactionConfirmDeleteView.as_view(), name='transaction_confirm_delete'),
]

moneycount/urls.py
from django.urls import path
from . import views

app_name = "moneycount"

urlpatterns = [
    # ユーザーがlocalhost:8000にアクセスしたときにプロジェクトのurls.pyを経由してたどり着くところ
    # viewsモジュール内のIndexViewを呼び出すためのもの。
    # これが呼び出されるとaccountアプリのurls.pyで定義しているhomeという名前のパスのページに移動するようになっている
    path('', views.IndexView.as_view(), name = 'home'),

    # コンタクトページにアクセスしたときに使用されるURLを提供
    path('contact/', views.ContactView.as_view(), name = 'contact'),
]

moneyproject/urls.py
from django.contrib import admin
from django.urls import path, include

# 一番最初にユーザーからアクセスがあったときに動き始めるのがこのファイル
# URLを見てどのアプリのページに飛ばすかを選択するための機能が備わっている

urlpatterns = [
    # adminが入っていたら管理者のページに移動するようにしている
    path("admin/", admin.site.urls),

    # localhost:8000にアクセスしたときにアプリのurls.pyのIndexViewのhome画面に移動するようになっている
    path('', include('moneycount.urls')),

    # アカウントのサインイン、サインアップなどregistrationディレクトリに入っているものに
    # アクセスが必要な場合にこっちが使われる
    path('', include('accounts.urls')),
]

moneycount/models.py
from django.db import models

# Create your models here.

moneycount/forms.py
# django.formsをインポート
from django import forms

class ContactForm(forms.Form):
    # フォームのフィールドをクラス変数として定義
    name = forms.CharField(label='名前')
    email =forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='件名')
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        '''ContactFormのコンストラクタ―
        
        フィールドの初期化を行う
        '''
        super().__init__(*args, **kwargs)
        # nameフィールドのplaceholderにメッセージを登録
        self.fields['name'].widget.attrs['placeholder'] = \
            '名前を入力してください'
        # nameフィールドを出力する<input>タグのclass属性を設定
        self.fields['name'].widget.attrs['class'] = 'form-control'

        # emailフィールドのplaceholderにメッセージを登録
        self.fields['email'].widget.attrs['placeholder'] = \
            'メールアドレスを入力してください'
        # emailフィールドを出力する<input>タグのclass属性を設定
        self.fields['email'].widget.attrs['class'] = 'form-control'

        # titleフィールドのplaceholderにメッセージを登録
        self.fields['title'].widget.attrs['placeholder'] = \
            '件名を入力してください'
        # titleフィールドを出力する<input>タグのclass属性を設定
        self.fields['title'].widget.attrs['class'] = 'form-control'

        # messageフィールドのplaceholderにメッセージを登録
        self.fields['message'].widget.attrs['placeholder'] = \
            'メッセージを入力してください'
        # messageフィールドを出力する<input>タグのclass属性を設定
        self.fields['message'].widget.attrs['class'] = 'form-control'

moneycount/views.py
from django.shortcuts import render

from django.views.generic.base import TemplateView

from django.views.generic import FormView

from django.urls import reverse_lazy

from .forms import ContactForm

from django.contrib import messages

from django.core.mail import EmailMessage

# indexとは最初に表示されるぺーじのこと。
# 俺はhome.htmlを最初に表示したいからhome.htmlをIndexViewにおいてOK
class IndexView(TemplateView):

    template_name = "home.html"


class ContactView(FormView):
    '''問い合わせページを表示するビュー
    
    フォームで入力されたデータを取得し、メールの作成と送信を行う
    '''

    # contact.htmlをレンダリングする
    template_name = 'contact.html'
    # クラス変数form_classにforms.pyで定義したContactFormを設定
    form_class = ContactForm
    # 送信完了後にリダイレクトするページ
    success_url = reverse_lazy('moneycount:contact')

    def form_valid(self, form):
        '''FormViewクラスのform_vaild()をオーバーライド
        
        フォームのバリデーションを通貨したデータがPOSTされたときに呼ばれるメール送信を行う
        
        parameters:
            form(object):ContactFormのオブジェクト
        Return:
            HttpResponseRedirectのオブジェクト
            オブジェクトをインスタンス化するとsuccess_urlで
            設定されているURLにリダイレクトされる
            '''
        # フォームに入力されたデータをフィールド名を指定して取得
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        title = form.cleaned_data['title']
        message = form.cleaned_data['message']

        # メールのタイトルの書式を設定
        subject = 'お問い合わせ: {}'.format(title)
        # フォームの入力データの書式を設定
        message = '送信者名: {0}\nメールアドレス: {1}\n タイトル:{2}\n メッセージ:\n{3}'.format(name, email, title, message)

        # # メールの送信元アドレス
        # from_email = 'at.apple319@gmail.com'
        # # 送信元のメールアドレス
        # to_list = ['at.apple319@gmail.com']

        # メールの送信元アドレス
        from_email = 'at.apple319@gmail.com'
        # 送信先のメールアドレス
        to_list = ['at.apple319@gmail.com']

        # EmailMessageオブジェクトを生成
        message = EmailMessage(subject=subject,body=message,from_email=from_email,to=to_list)
        # EmailMessageクラスのsend()でメールサーバーからメールを送信
        message.send()
        # 送信完了後に表示するメッセージ
        messages.success(self.request, 'お問い合わせは正常に送信されました。')
        # 戻り値はスーパークラスのform_vaild()の戻り値(HttpResponseRedirect)
        return super().form_valid(form)

moneycount/templates/base.html
{% load static %}

<!-- 全部のページのひながたになるhtmlファイル -->
<!-- 基本的にヘッダー、フッターとbodyの中にそれぞれのページでcontentsをぶっこむためのスペースを用意 -->

<!-- ヘッド要素 -->
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <!-- ヘッダー -->
    <header>
        <div class="header">
            <!-- タイトル表示 -->
            <h1>{% block header_title %}＄Money Count＄{% endblock %}</h1>
        </div>
    </header>

    <!-- 写真 -->
    <div background = 'C:\djangoprojects\moneyproject\moneycount\static\img\ichimanen.img'>

    </div>
    <!-- タイトル用 -->
    <div class="title">
        <h2>お金の貸し借りを管理しましょう</h2>
        <h4>誰でも簡単にお金の貸し借りを管理できます。貸し借りなどのお金の問題を解消できます</h4>
    </div>

    <!-- 区切り -->
    <div class="line">
        <hr>
    </div>

    <!-- メインコンテンツをぶっこむ場所 -->
    <main>
        {% block contents %}{% endblock %}
    </main>

    <!-- フッター -->
    <footer>
        <hr>
        <p>&copy; MoneyCount hokahoka 2023</p>
    </footer>
</body>
</html>

moneycount/templates/contact.html
<!-- base.htmlのひな型を使用するために引っ張ってくる -->
{% extends 'base.html' %}

{% load static %}

<!-- タイトルのところにContactと表示する -->
{% block title %}Contact{% endblock %}

<!-- コンタクトぺーじのためのコンテンツをぶっこむためのもの -->
{% block contents %}
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <strong>連絡を取りたいですか？以下のフォームに入力し送信してください</strong>
                {% if messages %}
                <ul class = 'list-unstyled' style = 'list-style: none;'>
                    {% for message in messages %}
                    <li {%if message.tags %} class ='{{ message.tags }}' {% endif %}>
                        {{ message }}
                    </li>
                    {% endfor %}
                </ul>
                {% endif %}

                <div class="my-5">
                    <form method = 'post'>
                        {% csrf_token %}
                        {% for field in form %}
                            <div class = 'form-floating'>
                                <div class = 'form-group floating-label-form-group controls'>
                                    {{ field.label_tag }}
                                    {{ field }}
                                    <p class = 'help-block text-danger'></p>
                                </div>
                            </div>
                        {% endfor %}
                        <br>
                        <button type = 'submit' class = 'btn btn-primary' id = 'sendMessageButton'>送信</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
<a href="{% url 'accounts:my_page' %}">マイページへ戻る</a>
{% endblock %}

moneycount/templates/home.html
<!-- base.htmlのひな型を引っ張ってくる -->
{% extends 'base.html' %}

<!-- タイトルをぶっこむ -->
{% block title %}
    Mobey Count - Signin / Login
{% endblock %}

{% load static %}

<!-- 一番最初のページ用のもの -->
<!-- サインアップとログインを選べるページ -->
{% block contents %}
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<h2 class="akirame">CSSは諦めました！</h2>
<div class="first-buttons">
    <li><a href="{% url 'accounts:signup' %}" class="text-white">サインアップ</a></li>
    <li><a href="{% url 'accounts:login' %}" class="text-white">ログイン</a></li>
</div>
{% endblock %}

moneycount/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign up{% endblock %}

    {% block contents %}

    <hr>
    <div class = "container">
        <div class = "row">
            <div class = "col offset-2">
                <h3>サインアップ</h3>
                <form method = "post">
                    {% csrf_token %}
                    {% for field in form %}
                        <p>
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.help_text %}
                                <small style="color: grey">{{ field.help_text }}</small>
                            {% endif %}
                        </p>
                    {% endfor %}
                    <p style="color: red">
                        ※パスワードの再設定に必要となりますので、メールアドレスをご登録ください。
                    </p>
                    <input type="submit" value="サインアップ">
                </form>
                <br>
                <p><a href="{% url 'moneycount:home' %}">
                    登録を中止してトップページに戻る</a>
                </p>
            </div>
        </div>
    </div>
    {% endblock %}    

moneycount/templates/signup_success.html
{% extends 'base.html' %}

{% block title %}Registration Complete{% endblock %}

    {% block contents %}

    <div class="container">
        <div class="row">
            <div class="col offset-4 py-4">
                <h3>登録が完了しました</h3>
                <p><a href="{% url 'accounts:login' %}">ログインはこちらから</a></p>
            </div>
        </div>
    </div>
    {% endblock %}

moneycount/templates/transaction_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Confirm Deletion{% endblock %}

{% block contents %}
  <h2>貸し借りの削除</h2>
  <p>貸し借りをを削除してもよろしいですか？ "{{ object }}"?</p>
  <form method="post" action="{% url 'accounts:transaction_confirm_delete' pk=object.pk %}">
    {% csrf_token %}
    <input type="submit" value="決定">
  </form>
  <a href="{% url 'accounts:transaction_list' %}">戻る</a>
{% endblock %}

moneycount/templates/transaction_list.html
{% extends 'base.html' %}

{% block title %}Transaction List{% endblock %}

{% block contents %}
  <h2>貸し借りのリスト</h2>

  <ul>
    {% for transaction in transactions %}
      <li>
        {{ transaction.description }} - {{ transaction.amount }} - {{ transaction.date }}
        <a href="{% url 'accounts:transaction_confirm_delete' transaction.pk %}">削除</a>
      </li>
    {% endfor %}
  </ul>

  <a href="{% url 'accounts:my_page' %}">マイページへ戻る</a>
{% endblock %}